/** CREATE TABLE PARAM */
CREATE TABLE PI_PARAM (
	PPA_ID VARCHAR(60) not null,
	PPA_VALUE VARCHAR(250) not null,
	CONSTRAINT PK_PARAM primary key (PPA_ID));

/** CREATE TABLE CATEGORY 1 */
CREATE TABLE PI_CATEGORY_1 (
	PC1_ID VARCHAR(60) not null,
	PC1_NAME VARCHAR(250) not null,
	CONSTRAINT PK_CATEGORY_1 primary key (PC1_ID));
	
/** CREATE TABLE CATEGORY 2 */
CREATE TABLE PI_CATEGORY_2 (
	PC2_ID VARCHAR(60) not null,
	PC2_NAME VARCHAR(250) not null,
	PC1_ID VARCHAR(60) not null,
	CONSTRAINT PK_CATEGORY_2 primary key (PC2_ID));
	
/** CREATE TABLE CATEGORY 3 */	
CREATE TABLE PI_CATEGORY_3 (
	PC3_ID VARCHAR(60) not null,
	PC3_NAME VARCHAR(250) not null,
	PC2_ID VARCHAR(60) not null,
	
	CONSTRAINT PK_CATEGORY_3 primary key (PC3_ID));
	
/** CREATE TABLE DIMENSION */	
CREATE TABLE PI_DIMENSION (
	PDI_ID VARCHAR(60) not null,
	PDI_NAME VARCHAR(250) not null,
	CONSTRAINT PK_DIMENSION primary key (PDI_ID));
	
/** CREATE TABLE FIELD */		
CREATE TABLE PI_FIELD (
	PFI_ID VARCHAR(60) not null,
	PFI_NAME VARCHAR(250) not null,
	CONSTRAINT PK_FIELD primary key (PFI_ID));
	
/** CREATE TABLE METRIC */		
CREATE TABLE PI_METRIC (
	PME_ID VARCHAR(60) not null,
	PME_NAME VARCHAR(250) not null,
	PC3_ID VARCHAR(60) not null,
	PME_DIMENSION VARCHAR(60),
	PME_UNIT VARCHAR(25),
	CONSTRAINT PK_METRIC primary key (PME_ID));
	
/** CREATE TABLE METRIC FIELDS */		
CREATE TABLE PI_METRIC_FIELDS (
	PME_ID VARCHAR(60) not null,
	PFI_ID VARCHAR(60) not null,
	CONSTRAINT PK_METRIC_FIELDS primary key (PME_ID,PFI_ID));
	
/** ADD FOREIGN KEY */
ALTER TABLE PI_CATEGORY_2
	ADD FOREIGN KEY (PC1_ID) REFERENCES PI_CATEGORY_1 (PC1_ID);

ALTER TABLE PI_CATEGORY_3
	ADD FOREIGN KEY (PC2_ID) REFERENCES PI_CATEGORY_2 (PC2_ID);

ALTER TABLE PI_METRIC
	ADD FOREIGN KEY (PC3_ID) REFERENCES PI_CATEGORY_3 (PC3_ID);
	
ALTER TABLE PI_METRIC_FIELDS
	ADD FOREIGN KEY (PME_ID) REFERENCES PI_METRIC (PME_ID);
	
ALTER TABLE PI_METRIC_FIELDS
	ADD FOREIGN KEY (PFI_ID) REFERENCES PI_FIELD (PFI_ID);